services:
  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_mysql
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql  
    networks:
      - custom_network
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 500M
      MAX_EXECUTION_TIME: 360000
    ports:
      - 8080:80
    networks:
      - custom_network  
    depends_on:
      - db

  web:
    image: wordpress
    container_name: ${PROJECT_NAME}_wordpress
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./:/var/www/html
    user: "${UID}:${GID}"  
    networks:
      - custom_network
    ports:
      - 80:80
    depends_on:
      - db

volumes:
  db:
  web:

networks:
  custom_network:
    driver: bridge
    name: ${PROJECT_NAME}_network        